"""Pierwsza migracja

Revision ID: 4e726ab9005d
Revises:
Create Date: 2024-11-26 14:30:42.891311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e726ab9005d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacja', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pracownik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.String(length=50), nullable=False),
    sa.Column('nazwisko', sa.String(length=50), nullable=False),
    sa.Column('data_zatrudnienia', sa.DateTime(), nullable=False),
    sa.Column('pensja', sa.Float(), nullable=False),
    sa.Column('podwyzka', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('punkty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pracownik_id', sa.Integer(), nullable=False),
    sa.Column('ilosc', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pracownik_id'], ['pracownik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('punkty')
    op.drop_table('pracownik')
    op.drop_table('historia')
    # ### end Alembic commands ###